# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: github-actions
    directory: / # scans workflows + actions
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Europe/Amsterdam
    labels: [dependencies, github-actions]
    # assignees: [mgm-sec]
    commit-message:
      prefix: "deps(actions)"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: pip
    directory: / # Scans pyproject.toml + poetry.lock
    schedule:
      interval: weekly
      day: monday
      time: "05:15"
      timezone: Europe/Amsterdam
    labels: [dependencies, python]
    # assignees: [mgm-sec]
    commit-message:
      prefix: "deps(python)"
      include: scope
    open-pull-requests-limit: 10
    cooldown:
      default-days: 5
      semver-major-days: 14
    groups:
      python-patch-minor:
        update-types: [patch, minor]
        patterns: ["*"]

  - package-ecosystem: docker
    directories: ["/", "/docker"]
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Amsterdam
    labels: [dependencies, docker]
    # assignees: [mgm-sec]
    commit-message:
      prefix: "deps(docker)"
    open-pull-requests-limit: 5
    groups:
      docker-patch-minor:
        update-types: [patch, minor]
        patterns: ["*"]
