services:
  app:
    build:
      context: .
      args:
        NEW_UID: ${NEW_UID:-1000}
        NEW_GID: ${NEW_GID:-1000}
      dockerfile: docker/Dockerfile
    environment:
        FASTAPI_CONFIG_PATH: /src/app.conf
    volumes:
      - ./:/src
    ports:
      - 6510:8080
